collections:
  staff:
    output: true
defaults:
  - scope:
      path: ""
      type: "staff"
    values:
      layout: "staff_member"
collections:
    - services
name: Creative Agency
url: http://creative.com
author:
    name: Mike
    email: mike@creative.com